base.rb, cluster.rb, lib/tendrl.rb, lib/tendrl/attribute.rb, lib/tendrl/flow.rb, lib/tendrl/object.rb, node.rb, spec/fixtures/definitions/ceph_integration.yaml, spec/fixtures/definitions/tendrl_definitions_gluster_integration.yaml, spec/fixtures/definitions/tendrl_definitions_node_agent.yaml
- Fixes create * api's inside a cluster.
- Introduces inventory api's for getting list of Nodes, Clusters, Volumes, Peers, etc, should work for anything a valid YAML file.
=> Create volume and inventory api

cluster.rb, docs/pools.adoc, lib/tendrl/flow.rb
Fixes loading right definition file when cluster_id is passed in the url.
=> Load cluster definition on cluster context

lib/tendrl/monitoring_api.rb, lib/tendrl/presenters/cluster_presenter.rb
Added attributes like nodes, utilization and globaldetails to cluster API.
Monitoring API integration: Handle exception in cases when configuration exists, but service is unreachable.
=> Cluster add new attributes & monitoring API exception handling

cluster.rb, node.rb, spec/cluster_spec.rb
API should validate existing objects against the requested object list before responding.
=> Unknown object fix

docs/clusters.adoc, docs/jobs.adoc, docs/nodes.adoc, docs/pools.adoc, docs/volumes.adoc
- Added authorization everywhere.
- Updated docs for Volume creation, jobs list
- Added doc for Start and Stop Gluster volume
=> Updated docs for jobs and volumes

app/controllers/monitoring_controller.rb, app/controllers/nodes_controller.rb, config.ru, lib/tendrl/monitoring_api.rb, spec/tendrl/monitoring_api_spec.rb
Added Monitoring API's for
- Nodes
- Single Cluster
- Ceph 
- Gluster
- Cluster CPU utilization
=> Nodes, Cluster and system monitoring API's

lib/tendrl/job.rb
Job messages API fix for empty body.
=> Job messages empty fix

tendrl-api.spec
=> Packaging: Fix not to update edited config files

app/controllers/monitoring_controller.rb, app/controllers/nodes_controller.rb, lib/tendrl/monitoring_api.rb, spec/spec_helper.rb
All cluster iops data `/monitoring/clusters/iops`
List of clusters iops data `/monitoring/clusters/iops?cluster_ids=xxx,xxx`
Response
https://gist.github.com/anivargi/866b6f344bf34918b3777279750f8dd9
=> Monitoring API clusters iops implementation

tendrl-api.service, tendrl-api.spec
Change service name from tendrl-apid to tendrl-api
=> Change service name to tendrl-api

lib/tendrl/presenters/cluster_presenter.rb
Gluster clusters bricks details with all, free and used.
Sample response is at https://gist.github.com/anivargi/4d879a5fa76ab2589d26aa43201d725d
=> Clusters list bricks details

app/controllers/users_controller.rb, docs/bricks.adoc
- Return 404 not found error when username does not exist
- Add documentation for BricksMapping creation and output
=> Fix users invalid username error

tendrl-api.service, tendrl-api.spec
=> Added service restart mechanism on reboot of the node

lib/tendrl/presenters/cluster_presenter.rb
Fixes https://github.com/Tendrl/api/issues/225
=> Add network attributes to cluster list

Makefile
=> Make snapshot support and auto release version update

app/controllers/authenticated_users_controller.rb, app/controllers/users_controller.rb, app/forms/user_form.rb, app/models/user.rb, app/presenters/user_presenter.rb, spec/controllers/authenticated_users_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/fixtures/user.json, spec/forms/user_form_spec.rb, spec/models/user_spec.rb, spec/spec_helper.rb
- `email_notifications` flag for user notification setting
- `/current_user` endpoint to provide logged in user details
=> Add email notification setting and current user endpoint

app/presenters/cluster_presenter.rb, docs/clusters.adoc
- Parse errors key before sending clusters API response
- Fix Import cluster doc
=> Add parsed errors to clusters api

app/controllers/users_controller.rb, app/models/user.rb, app/presenters/user_presenter.rb, spec/controllers/authenticated_users_controller_spec.rb, spec/controllers/clusters_controller_spec.rb, spec/controllers/jobs_controller_spec.rb, spec/controllers/nodes_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/fixtures/access_token.json, spec/fixtures/dwarner.json, spec/fixtures/quentin.json, spec/fixtures/thardy.json, spec/fixtures/users.json, spec/models/user_spec.rb, spec/spec_helper.rb
- Allow admins to perform user management
- Disallow roles updating
- Allow current user to update self
- Allow admin to delete other users except admins
- Create email notifications indexes
=> Fix user management permission issues

app/controllers/clusters_controller.rb, app/controllers/nodes_controller.rb, app/models/alert.rb, app/models/brick.rb, app/models/node.rb, app/models/notification.rb, app/models/volume.rb, app/presenters/brick_presenter.rb, app/presenters/cluster_presenter.rb, app/presenters/volume_presenter.rb, lib/tendrl.rb, spec/controllers/clusters_controller_spec.rb, spec/controllers/nodes_controller_spec.rb
- Volume bricks details API `/clusters/:cluster_id/volumes/:volume_id/bricks`
- Node bricks details API `/clusters/:cluster_id/nodes/:node_id/bricks`
- Import cluster state attributes
- Alerting tags key json parsing
=> Add volumes bricks and nodes bricks API

tendrl-api.spec
=> Add log and tmp directories in the data directory

tendrl-api.spec
=> Add missing tendrl-ssl.conf.sample file

tendrl-api.spec
=> Change etcd.yml file permission to 640

tendrl-api.spec
=> Add rubygem-builder dependency

tendrl-api.spec
=> Remove packaging tendrl-api-doc

tendrl-api.spec
Fix RPM test for TPS
tendrl-bug-id: Tendrl/api#336
=> Supress service enable message during package update

app/controllers/clusters_controller.rb, app/presenters/job_presenter.rb, app/presenters/notification_presenter.rb
=> Update clusters_controller.rb (Add notifications api)

app/controllers/clusters_controller.rb
=> Add each node's bricks count to `clusters/:cluster_id/nodes` API

app/controllers/clusters_controller.rb, app/presenters/notification_presenter.rb
=> Renamed cluster_id as integration_id

app/controllers/clusters_controller.rb, app/presenters/cluster_presenter.rb, spec/controllers/clusters_controller_spec.rb, spec/spec_helper.rb
tendrl-bug-id: Tendrl/gluster-integration#553
=> Added REST endpoints for start/stop volume profiling

app/controllers/clusters_controller.rb, app/presenters/job_presenter.rb, app/presenters/notification_presenter.rb
=> Fixed a regression with notification presenter

docs/clusters.adoc
=> Added documentation for un-manage cluster REST endpoint

docs/clusters.adoc, spec/fixtures/cluster.json, spec/fixtures/managed_clusters.json, spec/fixtures/unmanaged_clusters.json
=> Update API docs and fixtures as per #359

README.adoc
=> Add build status for unit and functional tests to README.adoc

app/controllers/jobs_controller.rb, lib/tendrl/http_response_error_handler.rb, spec/controllers/jobs_controller_spec.rb, spec/spec_helper.rb
=> Return 404 for job-related APIs when job is absent

app/controllers/clusters_controller.rb, docs/clusters.adoc, spec/controllers/clusters_controller_spec.rb
Fixes: #384
tendrl-bug-id: Tendrl/api#384
=> Add API for getting individual cluster details

app/controllers/clusters_controller.rb, spec/controllers/clusters_controller_spec.rb
Fixes: #391
tendrl-bug-id: Tendrl/api#391
=> Add Cluster namespace to volume_profiling_flag

app/controllers/clusters_controller.rb
Fixes: #391
tendrl-bug-id: Tendrl/api#391
=> Fix volume profiling flag

app/controllers/clusters_controller.rb
tendrl-bug-id: Tendrl/gluster-integration#591
=> Corrected the parameter name while flow call

app/controllers/clusters_controller.rb, spec/controllers/clusters_controller_spec.rb, spec/fixtures/definitions/gluster.yaml
=> Corrected cluster/:cluster-id/profiling to submit a job

spec/fixtures/definitions/ceph.yaml, spec/fixtures/definitions/master.yaml, spec/tendrl/flow_spec.rb
Fixes: #406
tendrl-bug-id: Tendrl/api#406
=> Update fixtures and remove outdated specs

app/presenters/cluster_presenter.rb, spec/controllers/clusters_controller_spec.rb, spec/fixtures/cluster.json
Fixes: #410
tendrl-bug-id: Tendrl/commons#888
=> Add short_name to cluster attributes whitelist

Rakefile, app/controllers/authenticated_users_controller.rb, app/controllers/clusters_controller.rb, app/controllers/jobs_controller.rb, app/controllers/nodes_controller.rb, app/controllers/users_controller.rb, app/forms/user_form.rb, app/models/alert.rb, app/models/brick.rb, app/models/cluster.rb, app/models/job.rb, app/models/node.rb, app/models/user.rb, app/presenters/brick_presenter.rb, app/presenters/job_presenter.rb, app/presenters/user_presenter.rb, config/initializers/etcd.rb, lib/tendrl.rb, lib/tendrl/http_response_error_handler.rb
Fixes: #412
tendrl-bug-id: Tendrl/commons#893
=> Handle serialized objects

app/controllers/clusters_controller.rb, app/controllers/jobs_controller.rb, app/models/node.rb
Also, fix job details API when job doesn't have children
tendrl-bug-id: Tendrl/commons#893
related: Tendrl/api#412
=> Fix node-bricks API

app/forms/user_form.rb, app/models/job.rb, app/models/user.rb, app/presenters/user_presenter.rb
Also,
- Remove notification index when user email notifications are disabled
- Minor fix to job model to surface job IDs for some jobs
tendrl-bug-id: Tendrl/api#415
Fixes: #415
=> Fix email notifications boolean in user API

app/models/brick.rb, app/presenters/brick_presenter.rb
tendrl-bug-id: Tendrl/api#418
Fixes: #418
=> Fix volume-bricks API

app/controllers/clusters_controller.rb
bugzilla: 1582375
tendrl-bug-id: Tendrl/commons#819
=> Optional flag Cluster.delete_telemetry_data for un-manage cluster

app/controllers/clusters_controller.rb, spec/controllers/clusters_controller_spec.rb
=> Bugfix to reset IOStream in unmanage API

app/models/job.rb
tendrl-bug-id: Tendrl/api#433
bugzilla: 1592487
=> Load_all function required job_id in job json which is created by API

docs/clusters.adoc
fixes https://github.com/Tendrl/api/issues/427
=> remove dashes

lib/tendrl.rb
=> Fix recursion over etcd keys when 'data' is present as a non-json

app/forms/user_form.rb, spec/controllers/users_controller_spec.rb, spec/forms/user_form_spec.rb
=> Add password length validation, 9-128 chars

config/apache.vhost-ssl.sample, config/apache.vhost.sample
bugzilla: 1590416
tendrl-bug-id: Tendrl/api#446
Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>
=> Running Grafana behind a reverse proxy

config/puma/production.rb
bugzilla: 1637977
tendrl-bug-id: Tendrl/api#453
=> Reducing number of puma thread to optimize memory utilization

config/tendrl-api_logrotate.conf, tendrl-api.spec
bugzilla: 1654183
tendrl-bug-id: Tendrl/api#455
=> Logrotate for tendrl-api log files
