Tendrl/api

Makefile, tendrl-api.spec
Fix source tar not found and
directory lib/tendrl/presenters/ not found error during rpmbuild
tendrl-bug-id: Tendrl/api#62
=> Packaging: fix build error

cluster.rb, node.rb
The commit fixes listing of cluster and node when they are empty, the server responds with a empty array instead of a error message.
=> Node and Cluster list fix

tendrl-api.spec
Spec file updated to fix tendrl-api build error
and add rubygem-activemodel, rubygem-bcrypt as a dependency as per
latest code update.
=> Packaging: fix tendrl-api build error and add new dependencies

tendrl-api.spec
Add Rakefile into tendrl-api
tendrl-bug-id: Tendrl/api#108
=> Fix service start issue due to missing Rakefile

app/controllers/sessions_controller.rb, lib/tendrl/presenters/node_presenter.rb
- Incorrect token sent to logout handled.
- GetNodeList endpoint ignores messages attribute
=> Logout and node list fixes

app/controllers/clusters_controller.rb, app/controllers/nodes_controller.rb, lib/tendrl/flow.rb, lib/tendrl/job.rb, spec/controllers/nodes_controller_spec.rb, spec/fixtures/definitions/ceph.yaml, spec/fixtures/definitions/gluster.yaml, spec/fixtures/definitions/master.yaml, spec/fixtures/detected_cluster.json, spec/spec_helper.rb, spec/tendrl/flow_spec.rb
- Added `master.yaml`, `gluster.yaml` and `ceph.yaml` as fixtures for flow tests
- Added tags per flow in job
- Find `detected_cluster_id` from the `node_ids` provided for ImportCluster
=> Use tags provided by individual flows

app/controllers/monitoring_controller.rb, lib/tendrl/monitoring_api.rb, lib/tendrl/notification.rb
Provides following API's
```
GET /monitoring/node/:node_id/memory
GET /monitoring/node/:node_id/swap
GET /monitoring/node/:node_id/throughput?type=cluster_network
GET /monitoring/node/:node_id/throughput?type=public_network
GET /monitoring/node/:node_id/iops
GET /monitoring/node/:node_id/storage
GET /monitoring/node/:node_id/cpu
```
```
GET /monitoring/cluster/:cluster_id/throughput?type=cluster_network
GET /monitoring/cluster/:cluster_id/throughput?type=public_network
GET /monitoring/cluster/:cluster_id/iops
GET /monitoring/cluster/:cluster_id/latency
```
sds_name could be ceph/gluster
```
GET /monitoring/system/:sds_name/throughput?type=cluster_network
GET /monitoring/system/:sds_name/throughput?type=public_network
```
=> Additional monitoring API's for iops, latency and throughput

tendrl-api.spec
Api now required tendrl-node-agent service which needs
tendrl-node-agent package.
=> Add tendrl-node-agent dependency

tendrl-api.spec
=> Copy SSL configuration file for apache

config/etcd.sample.yml
Change etcd.sample.yml so that it's not necessary to edit user_name
or password values when etcd authentication is disabled. This simplifies
both installation guide and tendrl-ansible.
tendrl-bug-id: Tendrl/api#294
=> etcd.sample.yml works without etcd auth by default

docs/alerts.adoc
Fixed API call as it was incorrect.  Documentation still said v1 when it should 1.0.
=> API call said ../api/v1/alerts vs. ../api/1.0/alerts

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/etcd.sample.yml, config/initializers/etcd.rb, lib/tendrl.rb, spec/controllers/authenticated_users_controller_spec.rb, spec/controllers/users_controller_spec.rb, tendrl-api.spec
Add config options in `etcd.yml` for adding certificate paths and passphrase. 
Load the etcd config only once on app preload.
=> Add etcd ssl certs config with preload

tendrl-api.service, tendrl-api.spec
=> Fix api daemon to run under non root user

Makefile
- unify `gitversion` target name across other Tendrl repos
- fix https://github.com/Tendrl/api/issues/361
- related to https://github.com/Tendrl/tendrl-ci/pull/8
=> rename make target update-release to gitversion

tendrl-api.spec
This patch will remove firewall configuration reload
from the spec file. Reloading firewall configuration
will be taken care by tendrl-ansible.
tendrl-bug-id: Tendrl/tendrl-ansible#49
=> Remove firewall configuration reload

.gitignore, tendrl-api.spec
This is a fix for #378, but requires verification.
We need to verify that the build process works, and all service-related functionality is maintained.
Adding vim tempfiles to .gitignore
=> Clean up service files on uninstall/upgrade

Rakefile, app/controllers/users_controller.rb, app/forms/user_form.rb, docs/users.adoc, spec/controllers/users_controller_spec.rb, spec/forms/user_form_spec.rb
This is backward-compatible because unknown parameters are simply
ignored.
Fixes: #106
=> Remove password_confirmation requirement

app/controllers/clusters_controller.rb
This fixes the expand API failing if it is the first API being hit after
service start.
Fixes: #400
tendrl-bug-id: Tendrl/api#400
=> Bugfix for expand edge case

app/controllers/clusters_controller.rb, spec/controllers/clusters_controller_spec.rb, spec/spec_helper.rb
Fixes: #397
tendrl-bug-id: Tendrl/api#397
=> Import job for unknown cluster now returns 404

app/controllers/users_controller.rb, app/forms/user_form.rb, spec/controllers/users_controller_spec.rb, spec/forms/user_form_spec.rb
bugzilla: 1610660
Since etcd does not allow renaming of keys, the only way to fix this is
to delete the existing user once the new one is created. UI does not allow editing username anyway.
=> Disallow updating username

tendrl-api.spec
bugzilla: 1677307
tendrl-bug-id: Tendrl/api#458
=> Renamed tendrl-ssl.conf.sample to tendrl-ssl.conf.sample

config/apache.vhost-ssl.sample, config/apache.vhost.sample
=> Modified %ssl_virtualhost_ip% to %hostname(fqdn)%
